spring:
  datasource:
    url: jdbc:postgresql//classdb.csvriryt3t5w.us-east-2.rds.amazonaws.com:5432/hibernate
    username: hibernate_role
    password: top-secret
      
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        temp:
          use_jdbc_metadata_default: false